services:
  - type: web
    name: fashion-store-chatbot
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: CHROMA_HOST
        sync: false
      - key: CHROMA_PORT
        sync: false
